// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoZ0i00H1drtpt53ZqbvshA57JOxvFY9o',
    appId: '1:608395316742:web:1d37827b538471fb3bfd87',
    messagingSenderId: '608395316742',
    projectId: 'examportal-d2650',
    authDomain: 'examportal-d2650.firebaseapp.com',
    storageBucket: 'examportal-d2650.appspot.com',
    measurementId: 'G-Q5NJB45HD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArG_TAsObccz2MWPjVjNlP5gs40jNOxtg',
    appId: '1:608395316742:android:7f84ceb8c4e454353bfd87',
    messagingSenderId: '608395316742',
    projectId: 'examportal-d2650',
    storageBucket: 'examportal-d2650.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5wi6Vwx6wXP0CBL4RlOXJW9XCMJlhJck',
    appId: '1:608395316742:ios:7cd2b6ee6a3ce9fb3bfd87',
    messagingSenderId: '608395316742',
    projectId: 'examportal-d2650',
    storageBucket: 'examportal-d2650.appspot.com',
    iosBundleId: 'com.example.examportal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5wi6Vwx6wXP0CBL4RlOXJW9XCMJlhJck',
    appId: '1:608395316742:ios:7cd2b6ee6a3ce9fb3bfd87',
    messagingSenderId: '608395316742',
    projectId: 'examportal-d2650',
    storageBucket: 'examportal-d2650.appspot.com',
    iosBundleId: 'com.example.examportal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoZ0i00H1drtpt53ZqbvshA57JOxvFY9o',
    appId: '1:608395316742:web:2d371bd56539a71e3bfd87',
    messagingSenderId: '608395316742',
    projectId: 'examportal-d2650',
    authDomain: 'examportal-d2650.firebaseapp.com',
    storageBucket: 'examportal-d2650.appspot.com',
    measurementId: 'G-K534M03YYT',
  );
}
